### ISSUE TITLE
FlutterPrinceOfVersions.checkForUpdatesFromGooglePlay  <asynchronous suspension>

### ISSUE THREAD

**Issue by conan1987** [infinum/flutter-prince-of-versions#12] opened 2021-07-15 11:43 UTC
Hi
I try to use this package to check for updates from play store but i get this error
FlutterPrinceOfVersions.checkForUpdatesFromGooglePlay (package:flutter_prince_of_versions/src/flutter_prince_of_versions.dart:65:5)
E/flutter ( 5217): <asynchronous suspension>
here is my code 
```dart
void initState()  {
    super.initState();
    DateTime now = new DateTime.now();
  DateTime date = new DateTime(now.year, now.month, now.day);
  print(date);
  update();
  }
Future<void> update() async{
  final Callback callback = MyCallback(context);
  await FlutterPrinceOfVersions.checkForUpdatesFromGooglePlay('https://play.google.com/store/apps/details?id=com.focus.ebook.FocusEbook', callback);

}
```
and i am using your callback class without any modifications .

**Comment by zenled** [comment] 2021-08-11 10:40
Hey.
Thank you for using this library. 
Unfortunately, I was not able to reproduce your problem.
Could you provide some more info, especially the info on the type of error you got.

**Comment by zenled** [comment] 2021-10-04 13:25
Closing since nothing can be done without more info.
Feel free to provide more info and open this task again.

**Closed by zenled** 2021-10-04 13:25 UTC
